TRC/urls.py
from django.contrib import admin
from django.urls import path,include
from TRC import views

urlpatterns = [
    path('admin_tools/', include('admin_tools.urls')),
    path('admin/', admin.site.urls),
	path('',views.view_index.as_view(),name='index'),
    path('',views.view_test.as_view(),name='test'),
	path('testform/',include('testform.urls',namespace='testform')),
	path('utilization/',include('utilization.urls',namespace='utilization')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
]

testform/urls.py
from django.urls import path
from testform import views
#template tagging
app_name = 'testform'

urlpatterns = [
    path('',views.view_testform.as_view(),name='view_testform'),
    path('blocks',views.view_testformTable.as_view(),name='view_testformList'),
    path('delete',views.view_testformTableDelete.as_view(),name='view_testformListDelete'),
    # path('blocks/<int:pk>',views.view_testformDetail.as_view(),name='view_testformDetail'),
    path('blocks/<int:pk>',views.view_testformUpdate.as_view(),name='view_testformUpdate'),
    path('blocks/<int:pk>/delete',views.view_testformDelete.as_view(),name='view_testformDelete'),
]

testform/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.conf import settings

class model_testform(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="author", null=True, blank=True, on_delete=models.SET_NULL)
    editBy = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="editBy", null=True, blank=True, on_delete=models.SET_NULL)
    parkSpecialLane = models.CharField(max_length=264)
    blockID = models.CharField(max_length=264,unique=True,error_messages={'unique':"This Block ID already exists."})
    consistantBlock = models.CharField(max_length=264)
    rodwayType = models.CharField(max_length=264)
    medianType = models.CharField(max_length=264)
    horAlignment = models.CharField(max_length=264)
    speedLimit = models.CharField(max_length=264)
    shoulderTypeDec = models.CharField(max_length=264)
    shoulderWidthDec = models.BigIntegerField(null=True,blank=True)
    gutterWidthDec = models.BigIntegerField(null=True,blank=True)
    rightLWidthDec = models.BigIntegerField(null=True,blank=True)
    centerLWidthDec = models.BigIntegerField(null=True,blank=True)
    LeftLWidthDec = models.BigIntegerField(null=True,blank=True)
    shoulderTypeInc = models.CharField(max_length=264)
    shoulderWidthInc = models.BigIntegerField(null=True,blank=True)
    gutterWidthInc = models.BigIntegerField(null=True,blank=True)
    rightLWidthInc = models.BigIntegerField(null=True,blank=True)
    centerLWidthInc = models.BigIntegerField(null=True,blank=True)
    LeftLWidthInc = models.BigIntegerField(null=True,blank=True)
    comment = models.CharField(max_length=264)
    state = models.CharField(max_length=264)

    def __str__(self):
        return self.blockID

    def get_absolute_url(self):
        return reverse('testform:view_testformUpdate', args=[str(self.pk)])

    def save_model(self, request, obj, form, change):
        obj.author = request.user
        super().save_model(request, obj, form, change)

testform/forms.py
from django import forms
#add form data to models
from testform.models import model_testform
from django.views.generic.edit import UpdateView
from django.core import validators

class form_testform(forms.ModelForm):
    parkSpecialLane = forms.ChoiceField(label='Parking Lane or Other Special Lane',choices=[("", ""),("N", "N"),("PK", "PK"),("SP", "SP"),("CLP", "CLP"),("BL", "BL"),("OTH", "OTH")])
    blockID = forms.CharField(label='Block ID', required = True)
    consistantBlock = forms.BooleanField(label='Consistant Block', required = False)
    rodwayType = forms.ChoiceField(required = False, label='Roadway Type',choices=[("", ""),("2U", "2U"),("3T", "3T"),("4U", "4U"),("4D", "4D"),("5T", "5T"),("6U", "6U"),("6D", "6D")])
    medianType = forms.ChoiceField(required = False, label='Median Type',choices=[("", ""),("N", "N"),("R", "R"),("D", "D"),("F", "F")])
    horAlignment = forms.ChoiceField(required = False, label='Horizontal Alignment',choices=[("", ""),("T", "T"),("GC", "GC"),("SC", "SC")])
    speedLimit = forms.ChoiceField(required = False, label='Speed Limit', choices=[(x, x) for x in range(0, 70, 5)])
    shoulderChoices = [("",""),("P",'P'),("T",'T'),("G",'G'),("C",'C'),("VC",'VC'),("MC",'MC'),("CG",'CG'),("MG",'MG'),("PC",'PC'),("N",'N')];
    shoulderTypeDec = forms.ChoiceField(required = False, label='Shoulder Type',choices=shoulderChoices)
    shoulderWidthDec = forms.IntegerField(required = False, label='Shoulder Width')
    gutterWidthDec = forms.IntegerField(required = False, label='Gutter Width')
    rightLWidthDec = forms.IntegerField(required = False, label='Right Lane Width')
    centerLWidthDec = forms.IntegerField(required = False, label='Center Lane Width')
    LeftLWidthDec = forms.IntegerField(required = False, label='Left Lane Width')
    shoulderTypeInc = forms.ChoiceField(required = False, label='Shoulder Type',choices=shoulderChoices)
    shoulderWidthInc = forms.IntegerField(required = False, label='Shoulder Width')
    gutterWidthInc = forms.IntegerField(required = False, label='Gutter Width')
    rightLWidthInc = forms.IntegerField(required = False, label='Right Lane Width')
    centerLWidthInc = forms.IntegerField(required = False, label='Center Lane Width')
    LeftLWidthInc = forms.IntegerField(required = False, label='Left Lane Width')
    comment = forms.CharField(required = False, label='Comments', widget=forms.Textarea)
    stateList=[("",""),("AL",'AL'),("AK",'AK'),("AZ",'AZ'),("AR",'AR'),("CA",'CA'),("CO",'CO'),("CT",'CT'),("DE",'DE'),("FL",'FL'),("GA",'GA'),("HI",'HI'),("ID",'ID'),("IL",'IL'),("IN",'IN'),("IA",'IA'),("KS",'KS'),("KY",'KY'),("LA",'LA'),("ME",'ME'),("MD",'MD'),("MA",'MA'),("MI",'MI'),("MN",'MN'),("MS",'MS'),("MO",'MO'),("MT",'MT'),("NE",'NE'),("NV",'NV'),("NH",'NH'),("NJ",'NJ'),("NM",'NM'),("NY",'NY'),("NC",'NC'),("ND",'ND'),("OH",'OH'),("OK",'OK'),("OR",'OR'),("PA",'PA'),("RI",'RI'),("SC",'SC'),("SD",'SD'),("TN",'TN'),("TX",'TX'),("UT",'UT'),("VT",'VT'),("VA",'VA'),("WA",'WA'),("WV",'WV'),("WI",'WI'),("WY",'WY')]
    state = forms.ChoiceField(required = False, label='State',choices=stateList)

    def clean_shoulderWidthDec(self):
        data = self.cleaned_data['shoulderWidthDec']
        print (data)
        if data == None:
            data = 1
        if data>50 or data<1:
            raise forms.ValidationError("Shoulder width out of range")
        return self.cleaned_data['shoulderWidthDec']

    class Meta:
        model = model_testform
        fields = '__all__'

testform/views.py
from django.shortcuts import render
from django.urls import reverse_lazy,reverse
from django.http import HttpResponseRedirect
from django.views.generic import CreateView,UpdateView,ListView,FormView,DeleteView,DetailView
from django_tables2 import SingleTableView,SingleTableMixin
from testform.forms import form_testform
from testform.tables import table_testform
from testform.models import model_testform
from django.contrib import messages
from django_filters.views import FilterView
from django.contrib.auth.decorators import login_required
import django_filters
from django.contrib.auth.models import User

class view_blockFilter(django_filters.FilterSet):
    blockID = django_filters.CharFilter(lookup_expr='exact')
    shoulderWidthDec = django_filters.CharFilter(lookup_expr='gte')

    class Meta:
        model = model_testform
        fields = {'blockID','shoulderWidthDec'}

class view_testformTable(SingleTableMixin,FilterView):
    model = model_testform
    table_class = table_testform
    template_name = 'testformList.html'
    filterset_class = view_blockFilter

    def blocks(self):
        return model_testform.objects.all()

class view_testformTableDelete(SingleTableMixin,FilterView):
    model = model_testform
    table_class = table_testform
    template_name = 'testformListDelete.html'
    filterset_class = view_blockFilter

    def blocks(self):
        return model_testform.objects.all()

class view_testformDetail(DetailView):
    model = model_testform
    context_object_name = 'testform_details'
    template_name = "testformDetail.html"

class view_testform(CreateView):
    model = model_testform
    form_class = form_testform
    template_name = "testform.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        form.save()
        return super(view_testform, self).form_valid(form)

    def get_success_url(self, *args, **kwargs):
        form = form_testform
        messages.add_message(self.request, messages.SUCCESS, 'New Block was submitted')
        return reverse("testform:view_testform")

class view_testformUpdate(UpdateView):
    model = model_testform
    form_class = form_testform
    template_name = "testformUpdate.html"
    # template_name_suffix = '_update_form'

    def form_valid(self, form):
        global subDel
        self.object = form.save(commit=False)
        self.object.editBy = self.request.user
        form.save()
        if self.request.POST.get("formsubmit"):
            subDel=1
        if self.request.POST.get("formdelete"):
            self.object.delete()
            subDel=2
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self, *args, **kwargs):
        form = form_testform
        if subDel==2:
            messages.add_message(self.request, messages.WARNING, 'Block was Deleted')
        if subDel==1:
            messages.add_message(self.request, messages.INFO, 'Block was Updated')
        return reverse("testform:view_testform")


class view_testformDelete(DeleteView):
    model = model_testform
    form_class = form_testform
    # template_name = "testformDelete.html"
    # template_name_suffix = '_delete_form'

    def get_success_url(self, *args, **kwargs):
        form = form_testform
        messages.add_message(self.request, messages.WARNING, 'Block was Deleted')
        return reverse("testform:view_testform")

testform/templates/testFormDetail.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title_block %}
testform
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'css/testform.css' %}">
<script type="text/javascript" src="{% static '/js/testform.js' %}"></script>
{% endblock %}

{% block body_block %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'testform:view_testform' %}">Block Site Tool</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'testform:view_testform' %}">New Block<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'testform:view_testformList' %}">Update Block</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'testform:view_testformListDelete' %}">Delete Block</a>
      </li>
    </ul>
  </div>
</nav>

<div id="map" class="map"></div>
<div class="row" id='mapRow'>
  <div class="col-md-2">
    <select id="layer-select">
      <option value="Aerial">Aerial</option>
      <option value="AerialWithLabelsOnDemand" selected>Aerial with labels</option>
      <option value="RoadOnDemand">Road</option>
      <option value="CanvasDark">Road dark</option>
      <option value="OrdnanceSurvey">Ordnance Survey</option>
    </select>
  </div>
  <div class="col-md-2">
    <span id="mouse-position"></span>
  </div>
  <div class="col-md">
    <form>
      <input type="textbox" id=coordtext placeholder="Enter Coordinates"></input>
      <button type='button' id='Get'>Submit</button>
    </form>
  </div>
  <div class="col-md">
    <form class="measuring-types">
        <span>Measurements: </span>
        <label>
          <input type="radio" name="measurement" value="LineString" checked> Distance
        </label>
        <label>
          <input type="radio" name="measurement" value="Polygon"> Area
        </label>
    </form>
  </div>
  <div class="col-md">
    <div class="result-wrapper">
      <span>Distance: </span>
      <samp id="js-result">n/a</samp>
    </div>
  </div>
</div>


<div class="container">

    <div class="fieldWrapper">

        <p id='consistency'>Consistency</p>

        <span title="Unique Segment ID"><p id="P_blockID">Block ID: {{testform_details.blockID}}</p></span>
        <span title="N – no parking lane and no other special lane
PK – parking lane present on outside of traveled way or parking explicitly marked by pavement markings
SP – parking is permitted on outside of traveled way but is not explicitly marked as a parking lane
CLP – parking is permitted only for part of the day on the outside-most traveled lane (curb lane)
BL – marked bicycle lane on roadway (sharrow markings alone do not constitute a bicycle lane; nor do off-road bicycle paths)
OTH – other special lane present">
        <p id="P_parkSpecialLane">Special Parking Lane: {{testform_details.parkSpecialLane}}</p></span>
        <p></p>
        Consistant Block:
        {{testform_details.consistantBlock}}
    </div>

    <div class="fieldWrapper">
        <p id='consistency'>Roadway Data</p>
        <span title="2U – two-lane undivided
3T – two-lane with center two way left turn lane
4U – four-lane undivided
4D – four-lane divided
5T – four-lane with center two-way left turn lane
6U – six-lane undivided
6D – six-lane divided">Roadway Type:</span>
        {{ testform_details.rodwayType }}<br>

        <span title="N – No median or median treatment (cross section with double yellow centerline)
R – Raised median (separated from roadway by a curb)
D – Depressed median (grass median with no curbs)
F – Flush median (paved median flush with paved roadway surface)">Median Type:</span>
        {{testform_details.medianType}}<br>

        <span title="T – Tangent
GC – Gentle Curves
SC – Sharp Curves">Horizontal Alignment:</span>
        {{testform_details.horAlignment}}<br>

        Speed Limit:
        {{testform_details.speedLimit}}
    </div>

    <div class="fieldWrapper">
        <p id='consistency'>Shoulder Data</p>
        <div class="row">
          <div class="col-md">
            <p id="shld">Decreasing</p>
            <span title="P – Paved shoulder
T – Turf shoulder
G – Gravel shoulder
C – Composite shoulder
VC – Vertical curb at edge of traveled way
MC – Sloping or mountable curve at edge of traveled way
CG – Vertical curb and gutter at edge of traveled way
MG – Sloping or mountable curb and gutter at edge of traveled way
PC  - Paved shoulder with curb at outside edge of shoulder
N – No shoulder (and no curb or curb and gutter)"><p>Shoulder Type: {{testform_details.shoulderTypeDec}}</p></span>
            <span title="Feet"><p>Shoulder Width: {{testform_details.shoulderWidthDec}}</p></span>
            <span title="Feet"><p>Gutter Width: {{testform_details.gutterWidthDec}}</p></span>
            <span title="Feet"><p>Right Lane Width: {{testform_details.rightLWidthDec}}</p></span>
            <span title="Feet"><p>Center Lane Width: {{testform_details.centerLWidthDec}}</p></span>
            <span title="Feet"><p>Left Lane Width: {{testform_details.LeftLWidthDec}}</p></span>
          </div>
          <div class="col-md">
            <p id="shld">Increasing</p>
            <span title="P – Paved shoulder
T – Turf shoulder
G – Gravel shoulder
C – Composite shoulder
VC – Vertical curb at edge of traveled way
MC – Sloping or mountable curve at edge of traveled way
CG – Vertical curb and gutter at edge of traveled way
MG – Sloping or mountable curb and gutter at edge of traveled way
PC  - Paved shoulder with curb at outside edge of shoulder
N – No shoulder (and no curb or curb and gutter)"><p>Shoulder Type: {{testform_details.shoulderTypeInc}}</p></span>
            <span title="Feet"><p>Shoulder Width: {{testform_details.shoulderWidthInc}}</p></span>
            <span title="Feet"><p>Gutter Width: {{testform_details.gutterWidthInc}}</p></span>
            <span title="Feet"><p>Right Lane Width: {{testform_details.rightLWidthInc}}</p></span>
            <span title="Feet"><p>Center Lane Width: {{testform_details.centerLWidthInc}}</p></span>
            <span title="Feet"><p>Left Lane Width: {{testform_details.LeftLWidthInc}}</p></span>

          </div>
        </div>
    </div>

    <br>
    <br>
    <p>Comment:</p>
    {{testform_details.comment}}
    <br><br>
    State:
    {{testform_details.state}}
    <br><br>

</div>


<script type="text/javascript" src="{% static '/js/openlayers.js' %}"></script>

{% endblock %}

testform/templates/testformDelete.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title_block %}
testfrom
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'css/testform.css' %}">
<script type="text/javascript" src="{% static '/js/testform.js' %}"></script>
{% endblock %}

{% block body_block %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'testform:view_testform' %}">Block Site Tool</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'testform:view_testform' %}">New Block<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'testform:view_testformList' %}">Update Block</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'testform:view_testformListDelete' %}">Delete Block</a>
      </li>
    </ul>
  </div>
</nav>

<div class="container">

  {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
  {% endif %}
  <form method="post">
    {% csrf_token %}

    <form method="post">{% csrf_token %}
        <h4>Are you sure you want to delete block {{ object.blockID }}?</h4>
        <button type="submit" class="btn btn-danger" id='formsubmit' >Delete</button>
    </form>

</div>

{% endblock %}

testform/templates/testformList.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load render_table from django_tables2 %}
{% load bootstrap3 %}

{% block title_block %}
testfrom
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'css/testform.css' %}">
<script type="text/javascript" src="{% static '/js/testform.js' %}"></script>
{% endblock %}

{% block body_block %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'testform:view_testform' %}">Block Site Tool</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'testform:view_testform' %}">New Block<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'testform:view_testformList' %}">Update Block</a>
      </li>
    </ul>
  </div>
</nav>


  <div class="jumbotron">
    <h1>Update Block Table</h1>

    {% comment %} <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Block ID Links
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        {% for blockid in view.blocks %}
            <a class="dropdown-item" href="list/{{blockid.pk}}">{{ blockid.blockID }}</a>
        {% endfor %}
      </div>
    </div>
    <br> {% endcomment %}
    {% if filter %}
      <form action="" method="get" class="form form-inline">
          {% bootstrap_form filter.form layout='inline' %}
            {% bootstrap_button 'filter' %}
      </form>
    {% endif %}

    <div class="" id="directable">
      {% render_table table%}
    </div>

  </div>


{% endblock %}

testform/templates/testformListDelete.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% load render_table from django_tables2 %}
{% load bootstrap3 %}

{% block title_block %}
testfrom
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'css/testform.css' %}">
<script type="text/javascript" src="{% static '/js/testform.js' %}"></script>
{% endblock %}

{% block body_block %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'testform:view_testform' %}">Block Site Tool</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'testform:view_testform' %}">New Block<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'testform:view_testformList' %}">Update Block</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'testform:view_testformListDelete' %}">Delete Block</a>
      </li>
    </ul>
  </div>
</nav>


  <div class="jumbotron">
    <h1>Delete Block Table</h1>

    <div class="dropdown">
      <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Block ID Links
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        {% for blockid in view.blocks %}
            <a class="dropdown-item" href="delete/{{blockid.id}}">{{ blockid.blockID }}</a>
        {% endfor %}
      </div>
    </div>
    <br>
    {% if filter %}
      <form action="" method="get" class="form form-inline">
          {% bootstrap_form filter.form layout='inline' %}
            {% bootstrap_button 'filter' %}
      </form>
    {% endif %}

    <div class="" id="directable">
      {% render_table table%}
    </div>
  </div>


{% endblock %}