TRC/urls.py
from django.contrib import admin
from django.urls import path,include
from TRC import views

urlpatterns = [
    path('admin_tools/', include('admin_tools.urls')),
    path('admin/', admin.site.urls),
	path('',views.view_index.as_view(),name='index'),
    path('',views.view_test.as_view(),name='test'),
	path('testform/',include('testform.urls',namespace='testform')),
	path('utilization/',include('utilization.urls',namespace='utilization')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
]

utilization/urls.py
from django.urls import path
from utilization import views
#template tagging
app_name = 'utilization'

urlpatterns = [
    path('',views.view_weekVarGet,name='view_weekVarGet'),
    path('newweek',views.view_utilization.as_view(),name='view_utilization'),
    path('edit-names',views.view_utilizationNames,name='view_utilizationNames'),
    path('edit-projects',views.view_utilizationProjects,name='view_utilizationProjects'),
]

utilization/models.py
from django.db import models

class model_name(models.Model):

    name = models.CharField(max_length=264,default="Name")

    def __str__(self):
        return self.name

class model_project(models.Model):

    projectDesc = models.CharField(max_length=264,default="Project")

    def __str__(self):
        return self.projectDesc

class model_utilization(models.Model):

    name = models.CharField(max_length=264)
    project = models.CharField(max_length=264)
    hours = models.FloatField(error_messages={'invalid':"Please enter hours or 0 to delete entry",'required':"Please enter hours or 0 to delete entry"})
    week = models.CharField(max_length=264)

    def __str__(self):
        return self.week+' '+self.name

    class Meta:
        ordering = ['name']

utilization/forms.py
from django import forms
from utilization.models import model_utilization,model_name,model_project

# model_utilization = None

class form_utilization(forms.ModelForm):

    name = forms.ModelChoiceField(queryset=model_name.objects.order_by('name').all(), empty_label=None, widget = forms.Select)
    project = forms.ModelChoiceField(queryset=model_project.objects.order_by('projectDesc').all(), empty_label=None)
    hours = forms.FloatField(error_messages={'invalid':"Please enter hours or 0 to delete entry",'required':"Please enter hours or 0 to delete entry"})
    week = forms.CharField(widget = forms.HiddenInput(),required=False)

    class Meta:
        model = model_utilization
        fields = '__all__'

utilization/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.views.generic import FormView,UpdateView
from utilization.forms import form_utilization
from utilization.models import model_utilization,model_name,model_project
from django.db.models import Sum
import datetime

week = ''

# model_utilization = None

class view_utilization(FormView):
    model = model_utilization
    form_class = form_utilization
    template_name = "utilization.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.week = week

        inputName = int(self.request.POST.get('name'))
        inputProj = int(self.request.POST.get('project'))
        inputHours = float(self.request.POST.get('hours'))
        inputName = model_name.objects.filter(id=inputName).values('name')[0].get('name')
        inputProj = model_project.objects.filter(id=inputProj).values('projectDesc')[0].get('projectDesc')

        model_utilization.objects.filter(name=inputName,project=inputProj,week=week).delete()
        if inputHours==0:
            print ('0',inputName,inputProj,week)
            model_utilization.objects.filter(name=inputName,project=inputProj,week=week).delete()
        elif week!='':
            form.save()
        else: return HttpResponseRedirect(reverse('utilization:view_weekVarGet'))
        return super(view_utilization, self).form_valid(form)

    def get_success_url(self, *args, **kwargs):
        form = form_utilization
        return reverse("utilization:view_utilization")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        totNameHrs = model_utilization.objects.filter(week=week).values('name').order_by('name').annotate(total_hours=Sum('hours'))
        totWeek = model_utilization.objects.filter(week=week).aggregate(Sum('hours'))
        totUtil = model_utilization.objects.exclude(project='PTO').filter(week=week).aggregate(Sum('hours'))
        context['week'] = week
        hrsNames = []
        hrsTot = []
        for values in totNameHrs:
            hrsNames.append(values.get('name',''))
            hrsTot.append(values.get('total_hours',0))
        try:
            totUtil = float(totUtil.get('hours__sum',0))
            totUtil = round(totUtil/(len(hrsNames)*40)*100)
        except: totUtil = 0
        context['hrsNames'] = hrsNames
        context['hrsTot'] = hrsTot
        context['totWeek'] = totWeek.get('hours__sum',0)
        context['totUtil'] = totUtil
        return context

    def utilList(self):
        return model_utilization.objects.order_by('name','project').filter(week=str(week))


def view_utilizationNames(request):
    namesModel = model_name.objects.order_by('name').values('name')
    if request.method == 'POST':
        if request.POST.get("delete"):
            delName = str(request.POST.get('delete'))
            delName = model_name.objects.filter(name=delName)
            delName.delete()
        elif request.POST.get("updateName"):
            currName = str(request.POST.get('currName'))
            updateName = str(request.POST.get('updateName'))
            model_name.objects.filter(name=currName).update(name=updateName)
        elif request.POST.get("new"):
            newName = str(request.POST.get('new'))
            nm = model_name(name=newName)
            nm.save()
        if week!='':
            return HttpResponseRedirect(reverse('utilization:view_utilization'))
        if week=='':
            return HttpResponseRedirect(reverse('utilization:view_weekVarGet'))
    return render(request,'utilizationNames.html',{'namesModel': namesModel})

def view_utilizationProjects(request):
    namesModel = model_project.objects.order_by('projectDesc').values('projectDesc')
    if request.method == 'POST':
        if request.POST.get("delete"):
            delName = str(request.POST.get('delete'))
            delName = model_project.objects.filter(projectDesc=delName)
            delName.delete()
        elif request.POST.get("updateName"):
            currName = str(request.POST.get('currName'))
            updateName = str(request.POST.get('updateName'))
            model_project.objects.filter(projectDesc=currName).update(projectDesc=updateName)
        elif request.POST.get("new"):
            newName = str(request.POST.get('new'))
            nm = model_project(projectDesc=newName)
            nm.save()
        if week!='':
            return HttpResponseRedirect(reverse('utilization:view_utilization'))
        if week=='':
            return HttpResponseRedirect(reverse('utilization:view_weekVarGet'))
    return render(request,'utilizationProjects.html',{'namesModel': namesModel})

def view_weekVarGet(request):
    global week
    utilModel = model_utilization.objects.order_by().values('week').distinct()
    today = datetime.datetime.today().date()
    if request.method == 'POST':
        if request.POST.get("currWeek"):
            week = today + datetime.timedelta(days=-today.weekday(), weeks=0)
        elif request.POST.get("nextWeek"):
            week = today + datetime.timedelta(days=-today.weekday(), weeks=1)
        else:
            week = datetime.datetime.strptime(request.POST.get('pastWeek'),r'%Y-%m-%d').date()
        return HttpResponseRedirect(reverse('utilization:view_utilization'))
    return render(request,'utilizationweek.html',{'utilModel': utilModel})

utilization/templates/utilization.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title_block %}
utilization
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'css/utilization.css' %}">
<script type="text/javascript" src="{% static '/js/utilization.js' %}"></script>
{% endblock %}

{% block body_block %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand">Utilization</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'utilization:view_weekVarGet' %}">Change Week<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'utilization:view_utilizationNames' %}">Edit Names<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'utilization:view_utilizationProjects' %}">Edit Projects<span class="sr-only">(current)</span></a>
      </li>

    </ul>
  </div>
</nav>

<div class="container" id="weekTable">
<div class="jumbotron">

<h2 style="text-align:center;">Week of {{ week }} {{ test }}</h2>
<br>
<div class="row">
  <div class="col-md">
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
  </div>
  <div class="col-md">
    <table>
      <tr>
        <th>Name</th>
        <th>Project</th>
        <th>Hours</th>
      </tr>
      {% for week in view.utilList %}
      <tr>
        <td>{{ week.name }}</td>
        <td>{{ week.project }}</td>
        <td style="text-align:right;">{{ week.hours }}</td>
      </tr>
      {% endfor %}
    </table>

  </div>
  </div>
  <h2>Totals</h2>
  <table>
    <tr>
      {% for name in hrsNames %}
      <th>
        {{ name }} <strong>|</strong>
      </th>
      {% endfor %}
    </tr>
    <tr>
      {% for hrs in hrsTot %}
      <td>
          {{ hrs }}
      </td>
      {% endfor %}
    </tr>
  </table>
  {% comment %} <p>Conn: {{ totConn }} <strong>|</strong> Grotheer: {{ totGrot }} <strong>|</strong> Potts: {{ totPott }} <strong>|</strong> Torbic: {{ totTorb }}</p> {% endcomment %}
  <br>
  <p>Week: {{ totWeek }}
  <br>Utilization: {{ totUtil }}%</p>

  </div>
</div>





{% endblock %}

utilization/templates/utilizationNames.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title_block %}
utilization
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'css/utilization.css' %}">
<script type="text/javascript" src="{% static '/js/utilization.js' %}"></script>
{% endblock %}

{% block body_block %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand">Utilization</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'utilization:view_weekVarGet' %}">Change Week<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'utilization:view_utilizationNames' %}">Edit Names<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'utilization:view_utilizationProjects' %}">Edit Projects<span class="sr-only">(current)</span></a>
      </li>

    </ul>
  </div>
</nav>

<div class="container">

  <div class="jumbotron">
    <h3>Update or Delete Name</h3>
      <br><br>
      <div class="row" id="updateRow">

        <div class="col-md">
          <form action="" method="post" class="form form-inline">
            {% csrf_token %}
            <p style="margin-top:10px">Enter new name</p>
            <input type="text" name="new" id="newName" value="" style="margin-right:100%;margin-bottom:10px">
            <button type="submit" class="btn btn-primary" value="Submit">New</button>
          </form>
        </div>

        <div class="col-md">
          <form action="" method="post" class="form form-inline">
            {% csrf_token %}
            <p style="margin-top:10px">Select name and enter updated name</p>
            <select name="currName" type="text" id="name" value="" style="margin-right:100%;margin-bottom:10px">
              {% for name in namesModel %}
                <option>{{ name.name }}</option>
              {% endfor %}
            </select>
            <input type="text" name="updateName" value="" style="margin-right:100%;margin-bottom:10px">
            <button type="submit" class="btn btn-primary" value="Submit">Update</button>
          </form>
        </div>

        <div class="col-md">
          <form action="" method="post" class="form form-inline">
            {% csrf_token %}
            <p style="margin-top:10px">Select name to delete</p>
            <select name="delete" type="text" id="name" value="" style="margin-right:100%;margin-bottom:10px">
              {% for name in namesModel %}
                <option>{{ name.name }}</option>
              {% endfor %}
            </select>
            <button type="submit" class="btn btn-danger" value="Submit">Delete</button>
          </form>
        </div>

      </div>
  </div>
</div>





{% endblock %}

utilization/templates/utilizationProjects.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title_block %}
utilization
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'css/utilization.css' %}">
<script type="text/javascript" src="{% static '/js/utilization.js' %}"></script>
{% endblock %}

{% block body_block %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand">Utilization</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'utilization:view_weekVarGet' %}">Change Week<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'utilization:view_utilizationNames' %}">Edit Names<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'utilization:view_utilizationProjects' %}">Edit Projects<span class="sr-only">(current)</span></a>
      </li>

    </ul>
  </div>
</nav>

<div class="container">

  <div class="jumbotron">
    <h3>Update or Delete Project</h3>
      <br><br>
      <div class="row" id="updateRow">

        <div class="col-md">
          <form action="" method="post" class="form form-inline">
            {% csrf_token %}
            <p style="margin-top:10px">Enter new project</p>
            <input type="text" name="new" id="newName" value="" style="margin-right:100%;margin-bottom:10px">
            <button type="submit" class="btn btn-primary" value="Submit">New</button>
          </form>
        </div>

        <div class="col-md">
          <form action="" method="post" class="form form-inline">
            {% csrf_token %}
            <p style="margin-top:10px">Select project and enter updated project</p>
            <select name="currName" type="text" id="name" value="" style="margin-right:100%;margin-bottom:10px">
              {% for name in namesModel %}
                <option>{{ name.projectDesc }}</option>
              {% endfor %}
            </select>
            <input type="text" name="updateName" value="" style="margin-right:100%;margin-bottom:10px">
            <button type="submit" class="btn btn-primary" value="Submit">Update</button>
          </form>
        </div>

        <div class="col-md">
          <form action="" method="post" class="form form-inline">
            {% csrf_token %}
            <p style="margin-top:10px">Select project to delete</p>
            <select name="delete" type="text" id="name" value="" style="margin-right:100%;margin-bottom:10px">
              {% for name in namesModel %}
                <option>{{ name.projectDesc }}</option>
              {% endfor %}
            </select>
            <button type="submit" class="btn btn-danger" value="Submit">Delete</button>
          </form>
        </div>

      </div>
  </div>
</div>





{% endblock %}

utilization/templates/utilizationweek.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block title_block %}
utilization
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'css/utilization.css' %}">
<script type="text/javascript" src="{% static '/js/utilization.js' %}"></script>
{% endblock %}

{% block body_block %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand">Utilization</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'utilization:view_weekVarGet' %}">Change Week<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'utilization:view_utilizationNames' %}">Edit Names<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'utilization:view_utilizationProjects' %}">Edit Projects<span class="sr-only">(current)</span></a>
      </li>

    </ul>
  </div>
</nav>

<div class="container">

  <div class="jumbotron">
    <h3>View previous week or start new week</h3>
      <br><br>
      <div class="row">
        <div class="col-md">
          <form action="" method="post" class="form form-inline">
            {% csrf_token %}
            <select name="pastWeek" type="text" id="pastWeek" value="">
              {% for week in utilModel %}
                <option>{{ week.week }}</option>
              {% endfor %}
            </select>
            <input type="submit" value="Submit" class="btn btn-primary">
          </form>

        </div>
        <div class="col-md">
          <form action="" method="post" class="form form-inline">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name='currWeek' value=1>Start Current Week</button>
          </form>
        </div>
        <div class="col-md">
          <form action="" method="post" class="form form-inline">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary" name='nextWeek' value=1>Start Next Week</button>
          </form>
        </div>
      </div>
  </div>
</div>

{% endblock %}