TRC/urls.py
from django.contrib import admin
from django.urls import path,include
from TRC import views

urlpatterns = [
    path('admin_tools/', include('admin_tools.urls')),
    path('admin/', admin.site.urls),
	path('',views.view_index.as_view(),name='index'),
    path('',views.view_test.as_view(),name='test'),
	path('testform/',include('testform.urls',namespace='testform')),
	path('utilization/',include('utilization.urls',namespace='utilization')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name="login.html"),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>
    {% block title_block %}

    {% endblock %}
  </title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <script src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v6.0.1/build/ol.js"></script>
  <link rel="stylesheet" href="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v6.0.1/css/ol.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block style_block %}

  {% endblock %}
  <link rel="stylesheet" href="{% static 'css/base.css' %}">

</head>

<body>

  <nav class="navbar navbar-light">
      <a href="{% url 'index' %}"><img src="{% static 'images/Logo-Color Tag.jpg' %}" alt=""></a>
      {% if user.is_authenticated %}
      <span class="navbar-text ml-auto" style="margin:15px">
        Welcome {{user}}
      </span>
      <a class="my-3 my-sm-3" href="{% url 'accounts:logout' %}">Log Out</a>
      {% else %}
      <a class="my-2 my-sm-0" href="{% url 'accounts:login' %}">Log In</a>
      {% endif %}
  </nav>

  {% if user.is_authenticated %}
      {% block body_block %}


      {% endblock %}
  {% else %}
      <br><br>
      <div class="container">
      <div class="jumbotron" style="backgroud-color:white!imporant; margin:25px">
        <h1 class="display-3">Transportation Research Center</h1>
        <p class="lead">Welcome to the MRIGlobal Transportation Research Center's homepage. If you are here to fill out a survey or use a tool please log in and go to the URL given. If you are
        unsure of the URL or log in information please contact: <br><br>Ingrid Potts <br>ipotts@mriglobal.org</p>
      </div>
      </div>

  {% endif %}

  {% block login_block %}


  {% endblock %}


</body>

</html>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title_block %}
Home Page
{% endblock %}

{% block style_block %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block body_block %}

<div class="container">
<div class="jumbotron" style="backgroud-color:white!imporant; margin:25px">
  <h1 class="display-3">TRC Hub</h1>
  <p class="lead">Welcome to the MRIGlobal Transportation Research Center's homepage. If you are here to fill out a survey or use a tool please go to the URL given. If you are
  unsure of the URL please contact: <br><br>Ingrid Potts <br>ipotts@mriglobal.org</p>
</div>
</div>

{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>


</div>




{% endblock %}